# -*- coding: utf-8 -*-
"""nlp[Research Paper Intelligent System].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSILnppdSCl2OBbhL9Zlz13w-PvTvNaI

# AI research power intelligent system

Problem  - get help to find the relevant paper

solution - semantic meaning search

steps -
1. data collection
2. Text extraction
3. nlp preprocessig and creation of embedding
4. implement sentence transformers
5. embedding store that is vector database
6. Semantic search
7. generate output
"""

!pip install datasets

from datasets import load_dataset

dataset = load_dataset("CShorten/ML-ArXiv-Papers", split="train")

print(dataset)

dataset[0]

import pandas as pd

df = pd.DataFrame(dataset)
df

df.columns

df = df[['title','abstract']]

df

df.shape

df = df.head(15000)

df.shape

df.isnull().sum()

df["paper_text"]=df["title"]+" "+df["abstract"]

df[["paper_text"]].head()

type(df[["paper_text"]].head())

df[["paper_text"]].head()

print(df["paper_text"].iloc[0])

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print(type(model))

df["paper_text"].fillna("").astype(str).str.replace("\n", " ", regex=False)
df["paper_text"]=df["paper_text"].str.strip()

sample_text=df["paper_text"].iloc[0]
sample_text

embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

embedding[:56]

sample_embedding=model.encode(df["paper_text"].head(5).to_list())

print(sample_embedding.shape)

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(sample_embedding[0].reshape(1,-1),
                               sample_embedding[1].reshape(1, -1))
print(similarity)

similarity = cosine_similarity(sample_embedding[1].reshape(1,-1),
                               sample_embedding[1].reshape(1, -1))
print(similarity)

for i in range(1, 5):
  sim=cosine_similarity(sample_embedding[0].reshape(1,-1),
                               sample_embedding[i].reshape(1, -1))
  print(sim)

"""# generate full embedding"""

import numpy as np

import os
import numpy as np
if os.path.exists("embedding.npy"):
    print("Loading saved embeddings")
    embedding = np.load("embedding.npy")
else:
    print("Generating embeddings")
    embedding = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )
    np.save("embedding.npy", embedding)
    print("Embeddings saved successfully!")

print(embedding.shape)
print(type(embedding))

embedding.dtype

!pip install faiss-cpu
import faiss

if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index")
    index = faiss.read_index("paper_faiss.index")
else:
    print("Creating new FAISS index")
    faiss.normalize_L2(embedding)
    index = faiss.IndexFlatIP(384)
    index.add(embedding)
    faiss.write_index(index, "paper_faiss.index")
    print("FAISS index saved successfully!")

query="deep learning for medical image analysis"
query_embedding= model.encode([query])
query_embedding.shape

faiss.normalize_L2(query_embedding)

D,I = index.search(query_embedding,5)
print(D)
print(I)

def search_paper(query, k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D, I = index.search(query_embedding, k)
  for score, idx in zip(D[0], I[0]):
    print("Similarity score", score)
    print("Title", df.iloc[idx]["title"][:500])

search_paper("deep learning for medical image analysis")

print(df.iloc[10466]["title"])

print(df.iloc[10466]["abstract"])

print(df.iloc[11873]["title"])

def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

D,I= search_paper("deep learning for medical image analysis")
print(D)
print(I)

def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])
    print()

search_paper("deep learning for medical image analysis")

!pip install transformers==4.46.3

from transformers import pipeline
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"

)

type(summarizer)

summary=summarizer(df.iloc[10466]["abstract"],max_length=120,min_length=40)
print(summary)

type(summary)

type(summary[0])

summary[0]["summary_text"]

for score, idx in zip(D[0],I[0]):
  print("Similarity score",score)
  print("Title",df.iloc[idx]["title"])
  print("Title",df.iloc[idx]["abstract"][:500])

  summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40)
  print(summary)
  print(summary[0]["summary_text"])
  print()

def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])
    print()

    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40, do_sample=False)
    print(summary)
    print(summary[0]["summary_text"])
    print()

search_and_summarize("Deep learning in medical imaging",k=5)

pip install keybert

from keybert import KeyBERT

kw_model = KeyBERT(model)

type(kw_model)#model = SentenceTransformer("all-MiniLM-L6-v2")

text=df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)

print(keywords)

print(type(keywords))

keywords=kw_model.extract_keywords(text, keyphrase_ngram_range=(1,2), stop_words="english")

print(keywords)

"""Additional Works-
It also tell about the entity or information of the important keywords by using Name Entity recognizers[NER].
But the problem is that NER is trained on generic dataset and it doesn't not know about the technical words like what is pytorch, and python, deeplearning and all that why i want that my model is also told about every important word that is show in keyword.

#Self work
## To find the definition, category, importance, application, related work for the entity or for the keywords.
##We use GEMINI_API_Key
"""

!pip install -q google-generativeai

import json
import time
import google.generativeai as genai

GEMINI_API_KEY = "AQ.Ab8RN6J8FozVTwMrSVMuEKX0SN4xyeqed5AjswUDtCk4ZbfezA"

genai.configure(api_key=GEMINI_API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

keywords

keyword_list = [k[0] for k in keywords]

print(keyword_list)

def explain_keyword(keyword):

    prompt = f"""
You are an AI Research Assistant.

Explain the following technical keyword extracted from a research paper.

Keyword:
{keyword}

Return ONLY valid JSON.

{{
    "entity":"",
    "category":"",
    "definition":"",
    "importance":"",
    "applications":[],
    "related_terms":[]
}}
"""

    response = model.generate_content(prompt)

    try:
        text = response.text.strip()

        if text.startswith("```json"):
            text = text.replace("```json","").replace("```","").strip()

        return json.loads(text)

    except Exception:

        return {
            "entity": keyword,
            "category": "Unknown",
            "definition": response.text
        }

entity_information = []

for word in keyword_list:

    print(f"Processing : {word}")

    try:

        info = explain_keyword(word)

        entity_information.append(info)

        time.sleep(2)

    except Exception as e:

        print(e)

from pprint import pprint

for entity in entity_information:

    pprint(entity)

    print("-"*80)

with open("paper_entities.json","w",encoding="utf-8") as f:

    json.dump(entity_information,
              f,
              indent=4,
              ensure_ascii=False)

print("Saved Successfully")

import pandas as pd

df = pd.DataFrame(entity_information)

df

"""Next class-
LLM
Langchain
Tools
RAG

##NLP DONE
"""



"""# Project 3-> Agentic AI"""

!pip install langchain-community

!pip install langchain_core

from langchain_core.tools import tool

@tool
def search_paper(query:str)-> str:
  "Search research paper from the faiss database and retun the most relevant result"

!pip install langchain-huggingface

from langchain_huggingface import HuggingFacePipeline

llm = HuggingFacePipeline(pipeline=summarizer)

llm

response =llm.invoke("ABSTRACTNow a day’s recommendation system has changed the style ofsearching the things of our interest. This is information filtering approach that is used to predict the preference of thatuser.The most popular areas where recommender system is appliedare books, news, articles, music, videos, movies etc. In thispaper we have proposed a movie recommendation systemnamed MOVREC. It is based on collaborative filteringapproach that makes use of the information provided by users,analyzes them and then recommends the movies that is bestsuited to the user at that time. The recommended movie list issorted according to the ratings given to these movies byprevious users and it uses K-means algorithm for this purpose.MOVREC also help users to find the movies of their choicesbased on the movie experience of other users in efficient andeffective manner without wasting much time in uselessbrowsing. This system has been developed in PHP usingDreamweaver 6.0 and Apache Server 2.0. The presentedrecommender system generates recommendations usingvarious types of knowledge and data about users, the availableitems, and previous transactions stored in customizeddatabases. The user can then browse the recommendationseasily and find a movie of their choice.KeywordsK-means, recommendation system, recommender system, datamining, clustering, movies, Collaborative filtering, Contentbased filtering")

print(response)

print(type(response))

